# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

eater = Source.create({name: "Eater Austin", description: "The 38 Essential Austin Restaurants, April '14", category: "Critic", website: "http://austin.eater.com/archives/2014/04/08/the-38-essential-austin-restaurants-april-14.php"})
Recommendation.create({restaurant: Restaurant.create({name: "Noble Sandwich Company"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "Szechuan House"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "Pho Saigon"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "Ramen Tatsu-Ya"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "Stiles Switch BBQ & Brew"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "Amaya's Taco Village"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "Franklin Barbecue"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "Vino Vino"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "Foreign & Domestic"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "Contigo Austin"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "Fricano's Deli & Catering"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "Uchiko"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "La Condesa"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "24 Diner"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "Parkside"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "Second Bar + Kitchen"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "Barley Swine"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "Veracruz All Natural"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "Lenoir Austin"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "Tamale House East"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "La Barbecue Cuisine Texicana"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "Clark's Oyster Bar"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "Easy Tiger"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "Nubian Queen Lola Cajun"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "Wink"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "Epicerie"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "Tacodeli"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "Blue Dahlia Bistro"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "Swift's Attic"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "Bufalina"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "Qui Restaurant"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "Salt & Time"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "El Meson"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "Bouldin Creek Cafe"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "Jack Allen's Kitchen"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "Micklethwait Craft Meats"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "Curra's Grill"}), source: eater})
Recommendation.create({restaurant: Restaurant.create({name: "Sway Thai"}), source: eater})
