require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe RecommendsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Recommend. As you add validations to Recommend, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RecommendsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all recommends as @recommends" do
      recommend = Recommend.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:recommends)).to eq([recommend])
    end
  end

  describe "GET show" do
    it "assigns the requested recommend as @recommend" do
      recommend = Recommend.create! valid_attributes
      get :show, {:id => recommend.to_param}, valid_session
      expect(assigns(:recommend)).to eq(recommend)
    end
  end

  describe "GET new" do
    it "assigns a new recommend as @recommend" do
      get :new, {}, valid_session
      expect(assigns(:recommend)).to be_a_new(Recommend)
    end
  end

  describe "GET edit" do
    it "assigns the requested recommend as @recommend" do
      recommend = Recommend.create! valid_attributes
      get :edit, {:id => recommend.to_param}, valid_session
      expect(assigns(:recommend)).to eq(recommend)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Recommend" do
        expect {
          post :create, {:recommend => valid_attributes}, valid_session
        }.to change(Recommend, :count).by(1)
      end

      it "assigns a newly created recommend as @recommend" do
        post :create, {:recommend => valid_attributes}, valid_session
        expect(assigns(:recommend)).to be_a(Recommend)
        expect(assigns(:recommend)).to be_persisted
      end

      it "redirects to the created recommend" do
        post :create, {:recommend => valid_attributes}, valid_session
        expect(response).to redirect_to(Recommend.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved recommend as @recommend" do
        post :create, {:recommend => invalid_attributes}, valid_session
        expect(assigns(:recommend)).to be_a_new(Recommend)
      end

      it "re-renders the 'new' template" do
        post :create, {:recommend => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested recommend" do
        recommend = Recommend.create! valid_attributes
        put :update, {:id => recommend.to_param, :recommend => new_attributes}, valid_session
        recommend.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested recommend as @recommend" do
        recommend = Recommend.create! valid_attributes
        put :update, {:id => recommend.to_param, :recommend => valid_attributes}, valid_session
        expect(assigns(:recommend)).to eq(recommend)
      end

      it "redirects to the recommend" do
        recommend = Recommend.create! valid_attributes
        put :update, {:id => recommend.to_param, :recommend => valid_attributes}, valid_session
        expect(response).to redirect_to(recommend)
      end
    end

    describe "with invalid params" do
      it "assigns the recommend as @recommend" do
        recommend = Recommend.create! valid_attributes
        put :update, {:id => recommend.to_param, :recommend => invalid_attributes}, valid_session
        expect(assigns(:recommend)).to eq(recommend)
      end

      it "re-renders the 'edit' template" do
        recommend = Recommend.create! valid_attributes
        put :update, {:id => recommend.to_param, :recommend => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested recommend" do
      recommend = Recommend.create! valid_attributes
      expect {
        delete :destroy, {:id => recommend.to_param}, valid_session
      }.to change(Recommend, :count).by(-1)
    end

    it "redirects to the recommends list" do
      recommend = Recommend.create! valid_attributes
      delete :destroy, {:id => recommend.to_param}, valid_session
      expect(response).to redirect_to(recommends_url)
    end
  end

end
